import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import SideBar from '@/components/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col h-screen relative overflow-hidden`}>
        <Navbar />
        <div className='h-full bg-white flex text-black p-4' data-theme="light">
          <SideBar />
          <div className='w-full h-full border border-base-content rounded-2xl p-5'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
